server:
    port: 8081
spring:
    application:
        name: 01-MiniProject-TraininngInstituteCouncellorPortal
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: root
        url: jdbc:mysql://localhost:3306/sachin
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: true